version: '3'
services:
  clsi:
    build: ./services/clsi
    ports:
      - "3013:3013"
    environment:
      LISTEN_ADDRESS: 0.0.0.0
      SANDBOXED_COMPILES: 'true'
      TEXLIVE_IMAGE: texlive/texlive
      TEXLIVE_IMAGE_USER: root
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: /data
    volumes:
      - ./compiles:/overleaf/services/clsi/compiles
      - ./cache:/overleaf/services/clsi/cache
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
